---
- include_role:
    name: docker

- name: Create build dir
  file:
    path: /tmp/build
    state: directory
  become: true

- name: Copy nginx Dockerfile
  copy:
    src: Dockerfile
    dest: /tmp/build/Dockerfile
  become: true

- name: Copy nginx.conf template
  vars:
    container_num: "{{ config.container_num }}"
  template:
    src: nginx.j2.conf
    dest: /tmp/build/nginx.conf
  become: true

- name: Build nginx image
  docker_image:
    name: nginx_balancer
    build:
      path: /tmp/build/
    source: build
    force_source: yes
  become: true

- name: Create network
  vars:
    mask: "{{ config.mask }}"
  docker_network:
    name: app_net
    ipam_config:
      - subnet: "{{ mask }}.0/24"
        gateway: "{{ mask }}.1"
  become: true

- name: Run nginx
  vars:
    mask: "{{ config.mask }}"
  docker_container:
    name: nginx
    image: nginx_balancer
    recreate: true
    state: started
    networks:
      - name: app_net
        ipv4_address: "{{ mask }}.100"
    ports:
      - "80:80"
    container_default_behavior: compatibility
  become: true
