---
- include_role:
    name: docker

- name: Login to DockerHub
  docker_login:
    username: "{{ docker_login }}"
    password: "{{ docker_pass }}"
  become: true

- name: Pull the image
  docker_image:
    name: "{{ config.app_image }}"
    source: pull
    state: present
  become: true

- name: Create containers
  docker_container:
    name: "{{ config.default_app_name }}{{ item }}"
    image: "{{ config.app_image }}"
    ports:
      - "500{{ item }}:5000"
    container_default_behavior: compatibility
    state: started
    
  with_sequence: count={{ config.container_num }}
  become: true

